# 1
on:
  # 2
  push:
    tags:
    - '*'
# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "17.x"
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
    - run: flutter --version
    - run: flutter clean cache
    - run: flutter pub get
    - name: Create .env file
      run: touch .env
    - run: flutter build apk --release --dart-define=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} --dart-define=GOOGLE_TRANSLATE_API_KEY=${{ secrets.GOOGLE_TRANSLATE_API_KEY }} --dart-define=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} --dart-define=DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }}
    - name: Rename file 
      run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/${{ github.ref_name }}.apk
    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/${{ github.ref_name }}.apk"
        token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}