# 1
on:
  # 2
  push:
    branches: [ "main" ]
    tags:
    - '*'

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "17.x"
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml
    - run: flutter --version
    - run: flutter pub get
    - run: flutter build apk --release
    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/app-release.apk"
        token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}